version: "3.7"
services:
  db:
    container_name: snaphs
    image: postgres
    volumes:
      - snap:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=snaphs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - snapnet
  snaphs-api:
    container_name: snaphs-api
    build:
      context: .
      dockerfile: Dockerfile.base
    image: snaphs-api:latest
    depends_on:
      - db
    ports:
      - "8089:8089"
    logging:
      driver: json-file
    networks:
      - snapnet
volumes:
  snap: {}
networks:
  snapnet:
    driver: bridge
